tcms/kiwi_auth/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.urls import reverse_lazy
from django.contrib.auth import views as contrib_auth_views

from tcms.kiwi_auth import views

urlpatterns = [
    url(r'^(?P<username>[\w.@+-]+)/profile/$', views.profile,
        name='tcms-profile'),

    url(r'^register/$', views.register, name='tcms-register'),
    url(r'^confirm/(?P<activation_key>[A-Za-z0-9\-]+)/$', views.confirm,
        name='tcms-confirm'),

    url(r'^login/$', views.LoginViewWithCustomTemplate.as_view(), name='tcms-login'),
    url(r'^logout/$',
        contrib_auth_views.LogoutView.as_view(next_page=reverse_lazy('tcms-login')),
        name='tcms-logout'),


    url(r'^passwordreset/$', contrib_auth_views.PasswordResetView.as_view(),
        name='tcms-password_reset'),
    url(r'^passwordreset/done/$', contrib_auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'),
    url(r'^passwordreset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        contrib_auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^passwordreset/complete/$',
        contrib_auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

tcms/report/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.views.generic.base import RedirectView

from . import views

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='overall/', permanent=True)),
    url(r'^overall/$', views.overall, name='report-overall'),
    url(r'^product/(?P<product_id>\d+)/overview/$', views.overview, name='report-overview'),
    url(r'^product/(?P<product_id>\d+)/build/$', views.ProductBuildReport.as_view(),
        name='report-overall-product-build'),
    url(r'^product/(?P<product_id>\d+)/version/$', views.ProductVersionReport.as_view(),
        name='report-overall-product-version'),
    url(r'^product/(?P<product_id>\d+)/component/$', views.ProductComponentReport.as_view(),
        name='report-overall-product-component'),
    url(r'custom/$', views.CustomReport.as_view(), name='report-custom'),
    url(r'^custom/details/$', views.CustomDetailReport.as_view(), name='report-custom-details'),

    url(r'^testing/$', views.TestingReport.as_view(), name='testing-report'),
    url(r'^testing/case-runs/$', views.TestingReportCaseRuns.as_view(),
        name='testing-report-case-runs'),
]

tcms/urls.py
# -*- coding: utf-8 -*-

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.i18n import JavaScriptCatalog

from grappelli import urls as grappelli_urls
from attachments import urls as attachments_urls
from modernrpc.core import JSONRPC_PROTOCOL
from modernrpc.core import XMLRPC_PROTOCOL
from modernrpc.views import RPCEntryPoint
from tcms.core import ajax
from tcms.core import views as core_views
from tcms.core.contrib.comments import views as comments_views
from tcms.core.contrib.linkreference import views as linkreference_views
from tcms.testplans import urls as testplans_urls
from tcms.testcases import urls as testcases_urls
from tcms.kiwi_auth import urls as auth_urls
from tcms.testruns import urls as testruns_urls
from tcms.testruns import views as testruns_views
from tcms.report import urls as report_urls


urlpatterns = [
    url(r'^$', core_views.dashboard, name='core-views-index'),
    url(r'^xml-rpc/', RPCEntryPoint.as_view(protocol=XMLRPC_PROTOCOL)),
    url(r'^json-rpc/$', RPCEntryPoint.as_view(protocol=JSONRPC_PROTOCOL)),
    url(r'^navigation/', core_views.navigation, name='iframe-navigation'),

    url(r'^grappelli/', include(grappelli_urls)),
    url(r'^admin/', admin.site.urls),

    url(r'^attachments/', include(attachments_urls, namespace='attachments')),

    # Ajax call responder
    url(r'^ajax/update/cases-actor/$', ajax.UpdateTestCaseActorsView.as_view(),
        name='ajax.update.cases-actor'),
    url(r'^management/tags/$', ajax.tags, name='ajax-tags'),

    # comments
    url(r'^comments/post/', comments_views.post, name='comments-post'),
    url(r'^comments/delete/', comments_views.delete, name='comments-delete'),

    # Account information zone, such as login method
    url(r'^accounts/', include(auth_urls)),

    # Testplans zone
    url(r'^plan/', include(testplans_urls.plan_urls)),
    url(r'^plans/', include(testplans_urls.plans_urls)),

    # Testcases zone
    url(r'^case/', include(testcases_urls.case_urls)),
    url(r'^cases/', include(testcases_urls.cases_urls)),

    # Testruns zone
    url(r'^run/', include(testruns_urls.run_urls)),
    url(r'^runs/', include(testruns_urls.runs_urls)),

    url(r'^caserun/(?P<case_run_id>\d+)/bug/$', testruns_views.bug, name='testruns-bug'),
    url(r'^caserun/comment-many/', ajax.comment_case_runs, name='ajax-comment_case_runs'),
    url(r'^caserun/update-bugs-for-many/', ajax.update_bugs_to_caseruns),

    url(r'^linkref/add/$', linkreference_views.add, name='linkref-add'),
    url(r'^linkref/remove/(?P<link_id>\d+)/$', linkreference_views.remove),

    # Report zone
    url(r'^report/', include(report_urls)),

    # JavaScript translations, see
    # https://docs.djangoproject.com/en/2.1/topics/i18n/translation/#django.views.i18n.JavaScriptCatalog
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns.extend([
        url(r'^500/$', TemplateView.as_view(template_name="500.html")),
        url(r'^404/$', TemplateView.as_view(template_name="404.html")),
    ])

    try:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]
    # in case we're trying to debug in production
    # and debug_toolbar is not installed
    except ImportError:
        pass


# Overwrite default 500 handler
# More details could see django.core.urlresolvers._resolve_special()
handler500 = 'tcms.core.views.server_error'

tcms/testcases/models.py
# -*- coding: utf-8 -*-
from datetime import datetime

from django.conf import settings
from django.urls import reverse
from django.db import models
from django.db.models import ObjectDoesNotExist

import vinaigrette

from tcms.core.models import TCMSActionModel
from tcms.core.utils.checksum import checksum
from tcms.core.history import KiwiHistoricalRecords
from tcms.issuetracker.types import IssueTrackerType
from tcms.testcases.fields import MultipleEmailField


AUTOMATED_CHOICES = (
    (0, 'Manual'),
    (1, 'Auto'),
    (2, 'Both'),
)


class NoneText:
    author = None
    case_text_version = 0
    action = ''
    effect = ''
    setup = ''
    breakdown = ''
    create_date = datetime.now()

    @classmethod
    def serialize(cls):
        return {}


class TestCaseStatus(TCMSActionModel):
    id = models.AutoField(
        db_column='case_status_id', max_length=6, primary_key=True
    )
    # FIXME: if name has unique value for each status, give unique constraint
    # to this field. Otherwise, all SQL queries filtering upon this
    #        field will cost much time in the database side.
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = "Test case status"
        verbose_name_plural = "Test case statuses"

    def __str__(self):
        return self.name

    @classmethod
    def get_proposed(cls):
        try:
            return cls.objects.get(name='PROPOSED')
        except cls.DoesNotExist:
            return None

    @classmethod
    def get_confirmed(cls):
        try:
            return cls.objects.get(name='CONFIRMED')
        except cls.DoesNotExist:
            return None

    @classmethod
    def string_to_instance(cls, name):
        return cls.objects.get(name=name)

    def is_confirmed(self):
        return self.name == 'CONFIRMED'


# register model for DB translations
vinaigrette.register(TestCaseStatus, ['name'])


class Category(TCMSActionModel):
    id = models.AutoField(db_column='category_id', primary_key=True)
    name = models.CharField(max_length=255)
    product = models.ForeignKey('management.Product', related_name="category",
                                on_delete=models.CASCADE)
    description = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = u'test case categories'
        unique_together = ('product', 'name')

    def __str__(self):
        return self.name


class TestCase(TCMSActionModel):
    history = KiwiHistoricalRecords()

    case_id = models.AutoField(primary_key=True)
    create_date = models.DateTimeField(db_column='creation_date', auto_now_add=True)
    is_automated = models.IntegerField(db_column='isautomated', default=0)
    is_automated_proposed = models.BooleanField(default=False)
    script = models.TextField(blank=True, null=True)
    arguments = models.TextField(blank=True, null=True)
    extra_link = models.CharField(max_length=1024, default=None, blank=True, null=True)
    summary = models.CharField(max_length=255)
    requirement = models.CharField(max_length=255, blank=True, null=True)
    alias = models.CharField(max_length=255, blank=True)
    notes = models.TextField(blank=True, null=True)

    case_status = models.ForeignKey(TestCaseStatus, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, related_name='category_case',
                                 on_delete=models.CASCADE)
    priority = models.ForeignKey('management.Priority', related_name='priority_case',
                                 on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='cases_as_author',
                               on_delete=models.CASCADE)
    default_tester = models.ForeignKey(settings.AUTH_USER_MODEL,
                                       related_name='cases_as_default_tester',
                                       blank=True,
                                       null=True,
                                       on_delete=models.CASCADE)
    reviewer = models.ForeignKey(settings.AUTH_USER_MODEL,
                                 related_name='cases_as_reviewer',
                                 null=True,
                                 on_delete=models.CASCADE)

    # FIXME: related_name should be cases instead of case. But now keep it
    # named case due to historical reason.
    plan = models.ManyToManyField('testplans.TestPlan', related_name='case',
                                  through='testcases.TestCasePlan')

    component = models.ManyToManyField('management.Component', related_name='cases',
                                       through='testcases.TestCaseComponent')

    tag = models.ManyToManyField('management.Tag', related_name='case',
                                 through='testcases.TestCaseTag')

    # todo: Auto-generated attributes from back-references:
    # 'texts' : list of TestCaseTexts (from TestCaseTexts.case)

    def __str__(self):
        return self.summary

    @classmethod
    def to_xmlrpc(cls, query=None):
        from tcms.xmlrpc.serializer import TestCaseXMLRPCSerializer
        from tcms.xmlrpc.utils import distinct_filter

        _query = query or {}
        qs = distinct_filter(TestCase, _query).order_by('pk')
        serializer = TestCaseXMLRPCSerializer(model_class=cls, queryset=qs)
        return serializer.serialize_queryset()

    @classmethod
    def create(cls, author, values):
        """
        Create the case element based on models/forms.
        """
        case = cls.objects.create(
            author=author,
            is_automated=values['is_automated'],
            is_automated_proposed=values['is_automated_proposed'],
            # sortkey = values['sortkey'],
            script=values['script'],
            arguments=values['arguments'],
            extra_link=values['extra_link'],
            summary=values['summary'],
            requirement=values['requirement'],
            alias=values['alias'],
            case_status=values['case_status'],
            category=values['category'],
            priority=values['priority'],
            default_tester=values['default_tester'],
            notes=values['notes'],
        )
        tags = values.get('tag')
        if tags:
            map(case.add_tag, tags)
        return case

    @classmethod
    def list(cls, query, plan=None):
        """List the cases with request"""
        from django.db.models import Q

        if not plan:
            queryset = cls.objects
        else:
            queryset = cls.objects.filter(plan=plan)

        if query.get('case_id_set'):
            queryset = queryset.filter(pk__in=query['case_id_set'])

        if query.get('search'):
            queryset = queryset.filter(
                Q(pk__icontains=query['search']) |
                Q(summary__icontains=query['search']) |
                Q(author__email__startswith=query['search'])
            )

        if query.get('summary'):
            queryset = queryset.filter(Q(summary__icontains=query['summary']))

        if query.get('author'):
            queryset = queryset.filter(
                Q(author__first_name__startswith=query['author']) |
                Q(author__last_name__startswith=query['author']) |
                Q(author__username__icontains=query['author']) |
                Q(author__email__startswith=query['author'])
            )

        if query.get('default_tester'):
            queryset = queryset.filter(
                Q(default_tester__first_name__startswith=query[
                    'default_tester']) |
                Q(default_tester__last_name__startswith=query[
                    'default_tester']) |
                Q(default_tester__username__icontains=query[
                    'default_tester']) |
                Q(default_tester__email__startswith=query[
                    'default_tester'])
            )

        if query.get('tag__name__in'):
            queryset = queryset.filter(tag__name__in=query['tag__name__in'])

        if query.get('category'):
            queryset = queryset.filter(category__name=query['category'].name)

        if query.get('priority'):
            queryset = queryset.filter(priority__in=query['priority'])

        if query.get('case_status'):
            queryset = queryset.filter(case_status__in=query['case_status'])

        # If plan exists, remove leading and trailing whitespace from it.
        plan_str = query.get('plan', '').strip()
        if plan_str:
            try:
                # Is it an integer?  If so treat as a plan_id:
                plan_id = int(plan_str)
                queryset = queryset.filter(plan__plan_id=plan_id)
            except ValueError:
                # Not an integer - treat plan_str as a plan name:
                queryset = queryset.filter(plan__name__icontains=plan_str)
        del plan_str

        if query.get('product'):
            queryset = queryset.filter(category__product=query['product'])

        if query.get('component'):
            queryset = queryset.filter(component=query['component'])

        if query.get('bug_id'):
            queryset = queryset.filter(case_bug__bug_id__in=query['bug_id'])

        if query.get('is_automated'):
            queryset = queryset.filter(is_automated=query['is_automated'])

        if query.get('is_automated_proposed'):
            queryset = queryset.filter(
                is_automated_proposed=query['is_automated_proposed'])

        return queryset.distinct()

    def add_bug(self, bug_id, bug_system_id, summary=None, description=None,
                case_run=None, bz_external_track=False):
        bug, created = self.case_bug.get_or_create(
            bug_id=bug_id,
            case_run=case_run,
            bug_system_id=bug_system_id,
            summary=summary,
            description=description,
        )

        if created:
            if bz_external_track:

tcms/core/contrib/comments/forms.py
# -*- coding: utf-8 -*-

from django.conf import settings
from django import forms
from django.utils.translation import ugettext_lazy as _

from django_comments.forms import CommentDetailsForm

COMMENT_MAX_LENGTH = getattr(settings, 'COMMENT_MAX_LENGTH', 10000)


class SimpleForm(CommentDetailsForm):
    name = forms.CharField(
        label=_("Name"), widget=forms.HiddenInput, max_length=50,
        required=False,
    )
    email = forms.EmailField(
        label=_("Email address"), widget=forms.HiddenInput, required=False
    )
    url = forms.URLField(
        label=_("URL"), widget=forms.HiddenInput,
        required=False
    )
    comment = forms.CharField(
        label=_('Comment'),
        widget=forms.Textarea,
        max_length=COMMENT_MAX_LENGTH,
        required=False,
    )

tcms/core/contrib/linkreference/forms.py
# -*- coding: utf-8 -*-

"""
Define forms for each request for validating request arguments
"""

from django import forms

from tcms.core.forms.fields import StripURLField


class AddLinkReferenceForm(forms.Form):
    """ Validate the argument within the request for adding new link """

    target_id = forms.IntegerField(
        error_messages={
            'required': 'target ID argument should appear in the request for '
                        'adding new link as long as the target argument.'})

    name = forms.CharField(
        max_length=64,  # same as the model
        error_messages={
            'required': 'You should name this new link.'})
    url = StripURLField(
        error_messages={
            'required': 'Missing URL.'})

tcms/templates/run/get_case_runs.html
<form id="id_form_case_runs">
<div class="mixbar"> 
	<span class="tit" style='float:left'>Cases: {{ test_case_runs_count }}</span>
	<ul class="btnBlue btnBlueFilter" id="showFilterBtn">
		<li class="btnBlueL"></li>
		<li class="btnBlueC"><a title="Click to show filter case-run options" id='filter_case_run'>Show filter options</a></li>
		<li class="btnBlueR"></li>
	</ul>
	<div class='right_float tit'>
		<input id="id_check_box_auto_blinddown" type="checkbox" />
		<label for="id_check_box_auto_blinddown" title="Automatically display next text case">Automatically</label>
		<input id="id_check_box_highlight" type="checkbox" />
		<label for="id_check_box_highlight" title="Highlight my assigned runs">Highlight</label>
	</div>
	<div>
		<div class="btnBlueCaserun">
			<span>Cases</span>
			<ul>
				{% if perms.testruns.add_testcaserun %}
				<li><a href="{% url "add-cases-to-run" test_run.run_id %}" class="addBlue9">Add</a></li>
				{% endif %}
				{% if perms.testruns.delete_testcaserun %}
				<li><a href="#" title="Remove selected cases form this test run" data-param="{{ test_run.run_id }}" class="removeBlue9 js-del-case">Remove</a></li>
				{% endif %}
				{% if perms.testruns.change_testcaserun %}
				<li><a href="#" title="Update the IDLE case runs to newest case text" href="javascript:void(0)" data-param="{% url 'testruns-update_case_run_text' test_run.pk %}" class="updateBlue9 js-update-case">Update</a></li>
				{% endif %}
				{% if perms.testruns.change_testcaserun %}
				<li><a href="#" title="Assignee this case(s) to other people" class="assigneeBlue9 js-change-assignee">Assignee</a></li>
				{% endif %}
			</ul>
		</div>
		<div class="btnBlueCaserun">
			<span>Status</span>
			<ul class="statusOptions">
				{% for tcrs in test_case_run_status %}
				<li><a value="{{ tcrs.pk }}" href="#" class="{{ tcrs|lower }}Blue9">{{ tcrs }}</a></li>
				{% endfor %}
			</ul>
		</div>
		<div class="btnBlueCaserun">
			<span>Bugs</span>
			<ul>
				<li><a href="javascript:void(0);" class="addBlue9 js-add-bugs">Add</a></li>
				<li><a href="javascript:void(0);" class="removeBlue9 js-remove-bugs">Remove</a></li>
			</ul>
		</div>
		<div class="btnBlueCaserun">
			<span>Comment</span>
			<ul>
				<li><a href="#" class="addBlue9 js-show-commentdialog">Add</a></li>
			</ul>
		</div>
	</div>
	<div class="clear"></div>
</div>
</form>
<form id="id_filter" action="." method="get" style='display:none'>
	<div style="border:1px solid #235D9F; margin:2px; padding:8px; background:#DEEAF7;">
		<input type="hidden" name="order_by" value="{{ REQUEST_CONTENTS.order_by }}" />
		<div class="leftlistinfo">
			<div class="listinfo">
				<span class="title"><label for="id_summary">Summary&nbsp;:</label></span>
				<input id="id_summary" type="text" name="case__summary__icontains" value="{{ REQUEST_CONTENTS.case__summary__icontains }}" />
			</div>
			<div class="listinfo">
				<span class="title"><label for="id_default_tester">Default tester&nbsp;:</label></span>
				<input id="id_default_tester" type="text" name="tested_by__email__startswith" value="{{ REQUEST_CONTENTS.tested_by__email__startswith }}" />
			</div>
			<div class="listinfo">
				<span class="title"><label for="id_assignee">Assignee&nbsp;:</label></span>
				<input id="id_assignee" type="text" name="assignee__email__startswith" value="{{ REQUEST_CONTENTS.assignee__email__startswith }}" />
			</div>
			<div class="listinfo">
				<span class="title"><label for="id_is_automated">Automated&nbsp;:</label></span>
				<select id="id_is_automated" name="case__is_automated">
					<option value="">--------</option>
										<option value="0">Manual</option>
										<option value="1">Auto</option>
				</select>
			</div>
		</div>
		<div class="rightlistinfo">
			<div class="listinfo">
				<span class="title"><label for="id_bug">Bug&nbsp;:</label></span>
				<input id="id_bug" type="text" name="case_run_bug__bug_id__in" value="{{ REQUEST_CONTENTS.case_run_bug__bug_id__in }}" />
				<span class='grey'>You can type multiple bugs by comma.</span>
			</div>
			<div class="listinfo">
				<span class="title"><label for="id_case_run_status">Status&nbsp;:</label></span>
				<select id="id_case_run_status" name="case_run_status__pk">
					<option value="">--------</option>
					{% for case_run_status in test_case_run_status %}
					<option value="{{ case_run_status.pk }}" {% if case_run_status.pk|escape == REQUEST_CONTENTS.case_run_status__pk %}selected="selected"{% endif %}>{{ case_run_status }}</option>
					{% endfor %}
				</select>
			</div>
			<div class="listinfo">
				<span class="title"><label for="id_priority">Priority&nbsp;:</label></span>
				<select id="id_priority" name="case__priority__pk">
					<option value="">--------</option>
					{% for priority in priorities %}
					<option value="{{ priority.pk }}" {% if priority.pk|escape == REQUEST_CONTENTS.case__priority__pk %}selected="selected"{% endif %}>{{ priority }}</option>
					{% endfor %}
				</select>
			</div>
			<div class="listinfo">
				<span class="title"><label for="id_tags">Tag&nbsp;:</label></span>
				<input id="id_tag" type="text" name="case__tag__name" value="{{ REQUEST_CONTENTS.case_tag__name }}" />
			</div>
		</div>
		<div class='clear'></div>
		<div class='button_box2'>
		<input type="submit" value='Search' />
		<input type="reset" value='Reset' />
	</div>
	</div>
</form>

<div class="mixbar fixed">
	<div class="tit" style="width: 50px; float: left; height: 100%; margin: 0px; text-align: center;">Tags:</div>
	<div style="margin-left: 50px; line-height:22px;" class="taglist">
		{% for tag in case_own_tags %}
		{{ tag }}&nbsp;&nbsp;<span class="grey">-</span>&nbsp;&nbsp;
		{% empty %}
		<span class="grey">No tags in cases</span>
		{% endfor %}
	</div>
</div>

{% include "run/table_caseruns.html" %}

<div id="addlink_dialog" title="Add Test Link">
	<p>All these fields are required.</p>
	<form>
		<fieldset style="padding:0; border:0; margin-top:25px;">
			<label for="testlog_name" style="display:block">Name <span style="color:red">*</span> (64 characters at most)</label>
			<input type="text" id="testlog_name" name="testlog_name" size="64"
				class="text ui-widget-content ui-corner-all"
				style="margin-bottom:12px; width:95%; padding: .4em; display:block"/>
			<label for="testlog_url" style="display:block">URL <span style="color:red">*</span></label>
			<textarea id="testlog_url" name="testlog_url" rows="3"
				class="text ui-widget-content ui-corner-all"
				style="width:95%; display:block"></textarea>
		</fieldset>
	</form>
</div>
	<script id="add_issue_form_template" type="text/x-handlebars-template">
{% verbatim %}
	<h4>{{ action_button_text }} bug</h4>
		<form id="add_issue_form">
			<input type="hidden" name="a" value="{{ a }}">
				{{#each hiddenFields}}
					<input type="hidden" name="{{ this.name }}" value="{{ this.value }}">
				{{/each}}
{% endverbatim %}
			<div class="bug_type" id="id_bug_type">Issue Tracker</div>
			<select name="bug_system_id" id="bug_system_id">
			{% for btr in bug_trackers %}
				<option value="{{ btr.pk }}" data-validation-regexp="{{ btr.validate_reg_exp }}">{{ btr.name }}</option>
			{% endfor %}
			</select>
			</br>
{% verbatim %}
                    {{#if show_bug_id_field}}
			<div id="bug-system" style="line-height:30px;">
				<div class="bug_id">Bug ID</div>
				<input type="text" name="bug_id">
                            {{#if show_add_to_bugzilla_checkbox}}
				</br>
				<input type="checkbox" name="bz_external_track" value="bz_external_track">&nbsp;
				<span class="use_bz_external_track">Check to add Test Case(s) to Issue Tracker</span>
                            {{/if}}
			</div>
			</br></br>
                    {{/if}}
			<div>
				<input type="submit" value="{{ action_button_text }}">
{% endverbatim %}
				<input type="button" value="Cancel" class="js-cancel-button" >
			</div>
		</form>
	</script>
	<script id="batch_add_comment_to_caseruns_template" type="text/x-handlebars-template">
		<ul>
			<li><b>Comments: </b></li>
			<li><textarea name="comments" id="commentText" style="width:100%;height:100px;"></textarea></li>
			<li>
				<button id="btnComment">Confirm</button>
				<button id="btnCancelComment">Cancel</button>
				<span id="commentsErr"></span>
			</li>
		</ul>
	</script>

tcms/templates/run/get_cc.html
{% load static %}

{% if not is_ajax %}
	<ul style="margin:0px;" class="js-cc-ul">
	{% for cc in test_run.cc.select_related.all %}
	<li>
            <a href="{% url "tcms-profile" cc.username %}">{{ cc.username }}</a>
		{% if perms.testruns.delete_testruncc %}
		<a href="javascript:void(0)" class="js-remove-cc" data-params='[{{ test_run.run_id }}, "{{ cc.username }}"]'><img src="{% static 'images/remove_small.png' %}" width="9" height="9" title="remove this tag" /></a>
		{% endif %}
	</li>
	{% endfor %}
	</ul>

	<div><a class="addlink js-add-cc" href="javascript:void(0)" data-param="{{ test_run.run_id }}">Add CC</a></div>

	{% if message %}
		<div id="message" class="hidden">{{ message }}</div>
	{% endif %}
{% else %}
	{% if message %}
	<div id="message" class="hidden">{{ message }}</div>
	{% endif %}
	{% for cc in test_run.cc.select_related.all %}
	<li>
		<a href="{% url "tcms-profile" cc.username %}">{{ cc.username }}</a>
		{% if perms.testruns.delete_testruncc %}
		<a href="javascript:void(0)" class="js-remove-cc" data-params='[{{ test_run.run_id }}, "{{ cc.username }}"]'><img src="{% static 'images/remove_small.png' %}" width="9" height="9" title="remove this tag" /></a>
		{% endif %}
	</li>
	{% endfor %}
{% endif %}

tcms/templates/run/status_progress.html
<div class='progress-bar' style='float:none'><div class='percent'><span id='complete_percent'>{{ status_stats.CompletedPercentage|floatformat:0 }}</span>%</div><div class='progress-inner' style='width:{{ status_stats.CompletedPercentage|floatformat:0 }}%;'><div class='progress-failed' style='width:{{ status_stats.FailurePercentage|floatformat:0 }}%;'></div></div></div>

tcms/templates/run/status_progress_patternfly.html
<span>{{ stats.CompletedPercentage|floatformat:0 }}% complete</span>
<div class="progress">
  <div class="progress-bar progress-bar-striped progress-bar-success" style="width: {{ stats.SuccessPercentage|floatformat:0}}%;"></div>
  <div class="progress-bar progress-bar-striped progress-bar-danger" style="width: {{ stats.FailurePercentage|floatformat:0 }}%"></div>
</div>